@base_url = {{$dotenv PROTOCOL}}://{{$dotenv HOST}}:{{$dotenv PORT}}
@api_url = {{$dotenv PROTOCOL}}://{{$dotenv HOST}}:{{$dotenv PORT}}/{{$dotenv BASE_HREF}}api/v1

### GET status
GET {{base_url}}/ HTTP/1.1

### GET routes - msg: "ok"
GET {{api_url}}/
Accept: application/json

### POST data
POST {{api_url}}/data HTTP/1.1
Content-Type: application/json

{
    "test": 1234,
    "tosi": true,
    "merkkijono": "toimii"
}
